{{- range .Values.apps }}
{{- if .config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-config
data:
  {{- range $key, $value := .config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
{{- end }}
{{- end }}