apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      initContainers:
      - name: wait-for-user
        image: mongo
        command:
          - sh
          - -c
          - |
            echo "Waiting for user mongodb_exporter..."
            until mongosh "mongodb://mongodb_exporter:mongopw@db-clusterip:27017/admin?authSource=admin" --eval "db.runCommand({ ping: 1 })" > /dev/null 2>&1; do
              echo "User is not ready yet, retrying..."
              sleep 5
            done
            echo "User exists, starting the exporter"

      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.37.0
          ports:
            - containerPort: 9216
              name: http-metrics
          args:
            - '--mongodb.uri=mongodb://mongodb_exporter:mongopw@db-clusterip:27017/admin?authSource=admin'
            - '--collect-all'
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter-service
  labels:
    app: mongodb-exporter-svc 
spec:
  selector:
    app: mongodb-exporter
  ports:
    - protocol: TCP
      port: 9216
      targetPort: http-metrics
      name: http-metrics
  type: ClusterIP
