{{- range .Values.apps }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app: {{ .label }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          {{- if or .config .secrets }}
          
          env:
            {{- $appName := .name }}
          
            {{- if .config }}
            {{- range $key, $_ := .config }}
            - name: {{ $key | upper }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $appName }}-config
                  key: {{ $key | lower }}
            {{- end }}
            {{- end }}
           
            {{- if .secrets }}
            {{- range $key, $_ := .secrets }}
            - name: {{ $key | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ $appName }}-secret
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          
          {{- end }}

          {{- if or .resources $.Values.defaultResources }}
          resources:
            {{- toYaml (default $.Values.defaultResources .resources) | nindent 12 }}
          {{- end }}

          {{- if .ports }}
          ports:
            {{- range .ports }}
            - containerPort: {{ .port }}
              protocol: TCP            
            {{- end -}}  
          {{- end -}}

          {{- if .volumes }}
          volumeMounts:
            {{- range .volumes }}
            - name: {{ .name }}-volume
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}

        {{- if .sidecars }}
        {{- range .sidecars }}
        {{- $sidecarName := . }}
        {{- $sidecarConfig := index $.Values.sidecars $sidecarName }}
        {{- if $sidecarConfig }}
        - name: {{ $sidecarName }}
          image: {{ $sidecarConfig.image }}
          {{- if $sidecarConfig.command }}
          command:
            {{- toYaml $sidecarConfig.command | nindent 12 }}
          {{- end }}
          {{- if $sidecarConfig.args }}
          args:
            {{- toYaml $sidecarConfig.args | nindent 12 }}
          {{- end }}
          {{- if $sidecarConfig.env }}
          env:
            {{- range $key, $value := $sidecarConfig.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if $sidecarConfig.ports }}
          ports:
            {{- range $sidecarConfig.ports }}
            - containerPort: {{ .port }}
              {{- if .name }}
              name: {{ .name }}
              {{- end }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- end }}
          {{- if $sidecarConfig.volumeMounts }}
          volumeMounts:
            {{- toYaml $sidecarConfig.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if $sidecarConfig.resources }}
          resources:
            {{- toYaml $sidecarConfig.resources | nindent 12 }}
          {{- end }}
        {{- else }}
        {{- fail (printf "Sidecar '%s' does not exist in sidecars for app '%s'" $sidecarName $.name) }}
        {{- end }}
        {{- end }}
        {{- end }}

      {{- if .volumes }}
      volumes:
        {{- range .volumes }}
        - name: {{ .name }}-volume
          persistentVolumeClaim:
            claimName: {{ .name }}-pvc
        {{- end }}
      {{- end }}

{{- end }}