apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-exporter-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mongodb-exporter-svc
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-exporter-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-clusterip-svc
  endpoints:
  - port: http
    path: /metrics
    interval: 10s
  namespaceSelector:
    matchNames:
    - default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-exporter-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend-clusterip-svc
  endpoints:
  - port: http-monitoring
    interval: 10s
    path: /metrics
  namespaceSelector:
    matchNames:
    - default