{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}-svc
spec:
  selector:
    app: {{ .selector }}
  type: {{ .type }}
  ports:
    - name: http
      port: {{ .port }}
      {{- if .targetPort  }}
      targetPort: {{ .targetPort }}
      {{- end }}
  {{- if eq .name "frontend-clusterip" }}
    - name: http-monitoring
      port: 9113
      targetPort: 9113
  {{- end }}
{{- end }}