{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}-svc
spec:
  selector:
    app: {{ .selector }}
  type: {{ .type }}
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      port: {{ .port }}
      {{- if .targetPort  }}
      targetPort: {{ .targetPort }}
      {{- end }}
    {{- end }}
{{- end }}