apiVersion: apps/v1
kind: Deployment
metadata:
  name: "stacknotes-svc"
  labels:
    app: "stacknotes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "stacknotes-svc"
  template:
    metadata:
      labels:
        app: "stacknotes-svc"
    spec:
      containers:
        - name: "stacknotes-svc"
          image: "stacknotes-backend"
          env:
            - name: NODE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: node_environment
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-cm
                  key: cors_allowed_origins
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: database_uri
                  optional: false
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: access_token_secret
                  optional: false
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: refresh_token_secret
                  optional: false
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3500
              protocol: TCP
          volumeMounts:
            - name: backend-volume
              mountPath: /app/logs
      volumes:
        - name: backend-volume
          persistentVolumeClaim:
            claimName: backend-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip
spec:
  selector:
    app: "stacknotes-svc"
  ports:
  - port: 80
    targetPort: 3500
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
data:
  node_environment: Development
  cors_allowed_origins: http://localhost:3000,http://localhost:5173,https://app.stacknotes.local
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  database_uri: mongodb://root:mongopw@db-clusterip:27017/stacknotes?authSource=admin
  access_token_secret: b94802f4675a1c374df3d61ec80bec89327ec9ec206b4d669524f543d04d46e7627e683d2674d09de0b2df5614c14fd9490bca954a5716c6c9b1327c6595a3dc
  refresh_token_secret: 9106c739cfbdf45f39d825beadc09ba66a137b9b04007760570f8888f6fc31346f26cb416f05832670b842eb951129f1525e8c466487e55780576bf0e82e07a1