- name: Install NodeJS from NodeSource
  hosts: backend
  become: true
  vars:
    node_version: "20"
    app_repo: https://github.com/davidlihor/StackNotes.git
    app_path: /opt/stacknotes
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
        state: present
        update_cache: true

    - name: Add GPG key NodeSource
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource Repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_lsb.codename }} main"
        state: present

    - name: Update cache and install node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true

    - name: Clone Repository
      ansible.builtin.git:
        repo: "{{ app_repo }}"
        dest: "{{ app_path }}"
        version: "main"
        force: true

    - name: Install npm dependencies
      ansible.builtin.command: npm install
      args:
        chdir: "{{ app_path }}/BACKEND"

    - name: Build project
      ansible.builtin.command: npm run build
      args:
        chdir: "{{ app_path }}/BACKEND"

    - name: Copy .env file securely
      ansible.builtin.copy:
        src: files/.env.backend
        dest: "{{ app_path }}/BACKEND/.env"
        owner: vagrant
        group: vagrant
        mode: "600"

    - name: Deploy Node.js systemd service
      ansible.builtin.copy:
        dest: /etc/systemd/system/stacknotes.service
        content: "{{ lookup('file', 'stacknotes.service') }}"
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Node.js backend
      ansible.builtin.systemd:
        name: stacknotes
        enabled: true
        state: started
