- name: Install NodeJS from NodeSource
  hosts: frontend
  become: true
  vars:
    node_version: "20"
    app_repo: https://github.com/davidlihor/StackNotes.git
    app_path: /opt/stacknotes
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - git
        state: present
        update_cache: true

    - name: Add GPG key NodeSource
      ansible.builtin.apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add NodeSource Repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_lsb.codename }} main"
        state: present

    - name: Update cache and install node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true

    - name: Clone Repository
      ansible.builtin.git:
        repo: "{{ app_repo }}"
        dest: "{{ app_path }}"
        version: "main"
        force: true

    - name: Install npm dependencies
      ansible.builtin.command: npm install
      args:
        chdir: "{{ app_path }}/FRONTEND"

    - name: Copy .env file securely
      ansible.builtin.copy:
        src: files/.env.frontend
        dest: "{{ app_path }}/FRONTEND/.env"
        owner: vagrant
        group: vagrant
        mode: "600"

    - name: Build project
      ansible.builtin.command: npm run build
      args:
        chdir: "{{ app_path }}/FRONTEND"

    - name: Install NGINX
      ansible.builtin.apt:
        name: nginx
        update_cache: true

    - name: Ensure NGINX service is running and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true

    - name: Copy custom nginx config
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Copy app to NGINX path
      ansible.builtin.copy:
        src: "{{ app_path }}/FRONTEND/dist/"
        dest: "/usr/share/nginx/html/"
        remote_src: true
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
