defaultResources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

prometheus:
  enabled: true
  namespaceSelector:
    matchNames:
      - default
      - stacknotes

services:
  - name: db-clusterip
    selector: mongodb-svc
    type: ClusterIP
    ports:
    - name: http
      port: 27017
    
  - name: backend-clusterip
    selector: stacknotes-svc
    type: ClusterIP
    ports:
    - name: http
      port: 80
      targetPort: 3500

  - name: frontend-clusterip
    selector: stacknotes-app
    type: ClusterIP
    ports:
    - name: http
      port: 80
    - name: http-monitoring
      port: 9113

  - name: mongodb-exporter
    selector: mongodb-exporter
    type: ClusterIP
    ports:
      - name: http-metrics
        port: 9216
        targetPort: http-metrics

apps:
  - name: mongodb-svc
    image:
      repository: mongo
      tag: latest
    label: stacknotes
    replicaCount: 1
    ports: 
      - port: 27017
    secrets:
      mongo_initdb_root_username: root
      mongo_initdb_root_password: mongopw
    volumes:
      - name: db
        mountPath: /data/db
        type: pvc

  - name: stacknotes-svc
    image: 
      repository: davidlihor/stacknotes-backend 
      tag: latest
    label: stacknotes
    replicaCount: 1
    ports: 
      - port: 3500
    config:
      node_environment: Development
      cors_allowed_origins: http://localhost:3000,http://localhost:5173,https://app.stacknotes.local
    secrets:
      database_uri: mongodb://root:mongopw@db-clusterip:27017/stacknotes?authSource=admin
      access_token_secret: b94802f4675a1c374df3d61ec80bec89327ec9ec206b4d669524f543d04d46e7627e683d2674d09de0b2df5614c14fd9490bca954a5716c6c9b1327c6595a3dc
      refresh_token_secret: 9106c739cfbdf45f39d825beadc09ba66a137b9b04007760570f8888f6fc31346f26cb416f05832670b842eb951129f1525e8c466487e55780576bf0e82e07a1
    volumes:
      - name: backend
        mountPath: /app/logs
        type: pvc
    initContainers:
      - wait-for-mongo

  - name: stacknotes-app
    image: 
      repository: davidlihor/stacknotes-frontend 
      tag: latest
    label: stacknotes
    replicaCount: 1
    ports: 
      - port: 80
      - port: 8080
    config:
      vite_api_url: https://api.stacknotes.local
    sidecars:
      - nginx-exporter

  - name: mongodb-exporter
    image: 
      repository: percona/mongodb_exporter  
      tag: "0.37.0"
    ports:
      - port: 9216
        name: http-metrics
    args:
      - '--mongodb.uri=mongodb://mongodb_exporter:mongopw@db-clusterip:27017/admin?authSource=admin'
      - '--collect-all'
    initContainers:
      - wait-for-user

sidecars:
  nginx-exporter:
    image:
      repository: nginx/nginx-prometheus-exporter
      tag: latest
    ports:
      - port: 9113
        name: metrics
    args:
      - "--nginx.scrape-uri=http://localhost:8080/nginx_status"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

initContainers:
  wait-for-mongo:
    image:
      repository: busybox
      tag: latest
    command: ['sh', '-c', 'until nc -z db-clusterip 27017; do echo waiting for mongo; sleep 2; done;']
  wait-for-user:
    image:
      repository: mongo
      tag: latest
    command:
      - sh
      - -c
      - |
        echo "Waiting for user mongodb_exporter..."
        until mongosh "mongodb://mongodb_exporter:mongopw@db-clusterip:27017/admin?authSource=admin" --eval "db.runCommand({ ping: 1 })" > /dev/null 2>&1; do
          echo "User is not ready yet, retrying..."
          sleep 5
        done
        echo "User exists, starting the exporter"